publishDir = "docs"
baseurl = "/"

title = "Blake Naccarato"
copyright = "© {year} Blake Naccarato"

[markup.highlight]
  codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.

[module.imports]
  path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy"
