main:
  - name: "About"
    url: "#about"
    weight: 1
  - name: Publications
    url: "#publications"
    weight: 2
  - name: "Experience"
    url: "#experience"
    weight: 3
  # - name: "Posts"
  #   url: "#posts"
  #   weight: 4
  # - name: "Projects"
  #   url: "#projects"
  #   weight: 5
